### ISSUE TITLE
Segmentation using Inclusion Body containing E. coli (very bloated cells)

### ISSUE THREAD

**Issue by SandorAlbert** [Jhsmit/ColiCoords#116]
Hello,

I was wondering if it's possible to segment inclusion body containing E. coli using ColiCoords. IB containing cells are usually very bloated, showing big white circles/cylinders. Thus, the contour of the cells are often not very clear and hard to detect using thresholding methods. 
This is part of my Master's Thesis and has been a big challenge so far. 

Best regards

**Comment by Jhsmit** [comment]
Most likely it's possible to do so using the `CNN` module. I've tested this on sample data with very low signal-to-noise values and if you have sufficient training data you will most likely get a good result.

You can find example code for segmentation on the GitHub repo with code accompanying the ColiCoords PlosONE paper [here](https://github.com/Jhsmit/ColiCoords-Paper/tree/master/figures/Figure_6). The `gui_annotate.py` file launches a GUI which can be used to generate training data, notebooks 02/03 are examples of training and applying the neural networks.

The neural networks used are an implementation of: 
Falk, T. et al. U-Net: deep learning for cell counting, detection, and morphometry. Nat Methods 16, 67–70 (2019)

**Comment by SandorAlbert** [comment]
Thank you for responding. I will try it out and hopefully succeed. Happy holidays and best regards!

**Comment by Jhsmit** [comment]
Ok, good luck, if you have any more questions feel free to reopen / make a new issue.
