### ISSUE TITLE
Implement Cell Width Property

### ISSUE THREAD

**Issue by guyazran** [Jhsmit/ColiCoords#117]
Hi,

I would like to request the adding of cell width as a property (and implementing its calculation) to the Cell class, where if length is the measurement of the long dimension of the cell, then width should be the measurement of the short dimension of the cell.

thx

**Comment by Jhsmit** [comment]
The width of the cell can be calculated from the radius (width = 2*radius). However, the radius of the cell is not as easily defined as the length. 

You can use the ``measure_r`` function for this ([docs](https://colicoords.readthedocs.io/en/latest/modules.html#colicoords.cell.CellList.measure_r)), where this function determines measures the radius from one of the images, usually the brightfield. 
The brightfield is of course just a very crude image of scattered light. The obtained value is likely not the distance from inner/outer membrane to the center but rather some value that is proportional to it.
I have written a post on the issue [here](https://www.jhsmit.org/post/cell_width/) and I have some more information in this which I'll post in the future.
