### ISSUE TITLE
overlay drawing errror #1

### ISSUE THREAD

**Issue by elizamw** [Jhsmit/ColiCoords#49]
Traceback (most recent call last):
  line 420, in paint
    p.drawImage(QtCore.QRectF(0,0,*shape), self.qimage)
TypeError: arguments did not match any overloaded call:
  drawImage(self, QRectF, QImage, QRectF, flags: Union[Qt.ImageConversionFlags, Qt.ImageConversionFlag] = Qt.AutoColor): argument 2 has unexpected type 'NoneType'
  drawImage(self, QRect, QImage, QRect, flags: Union[Qt.ImageConversionFlags, Qt.ImageConversionFlag] = Qt.AutoColor): argument 1 has unexpected type 'QRectF'
  drawImage(self, Union[QPointF, QPoint], QImage, QRectF, flags: Union[Qt.ImageConversionFlags, Qt.ImageConversionFlag] = Qt.AutoColor): argument 1 has unexpected type 'QRectF'
  drawImage(self, QPoint, QImage, QRect, flags: Union[Qt.ImageConversionFlags, Qt.ImageConversionFlag] = Qt.AutoColor): argument 1 has unexpected type 'QRectF'
  drawImage(self, QRectF, QImage): argument 2 has unexpected type 'NoneType'
  drawImage(self, QRect, QImage): argument 1 has unexpected type 'QRectF'
  drawImage(self, Union[QPointF, QPoint], QImage): argument 1 has unexpected type 'QRectF'
  drawImage(self, QPoint, QImage): argument 1 has unexpected type 'QRectF'
  drawImage(self, int, int, QImage, sx: int = 0, sy: int = 0, sw: int = -1, sh: int = -1, flags: Union[Qt.ImageConversionFlags, Qt.ImageConversionFlag] = Qt.AutoColor): argument 1 has unexpected type 'QRectF'

**Comment by Jhsmit** [comment]
fixed by bbe8b7b6f554485a5166dab9745d7f725d134fc3
