### ISSUE TITLE
Error after final image loaded

### ISSUE THREAD

**Issue by elizamw** [Jhsmit/ColiCoords#55]
p.drawImage(QtCore.QRectF(0,0,*shape), self.qimage)
TypeError: arguments did not match any overloaded call:
  drawImage(self, QRectF, QImage, QRectF, flags: Union[Qt.ImageConversionFlags, Qt.ImageConversionFlag] = Qt.AutoColor): argument 2 has unexpected type 'NoneType'
  drawImage(self, QRect, QImage, QRect, flags: Union[Qt.ImageConversionFlags, Qt.ImageConversionFlag] = Qt.AutoColor): argument 1 has unexpected type 'QRectF'
  drawImage(self, Union[QPointF, QPoint], QImage, QRectF, flags: Union[Qt.ImageConversionFlags, Qt.ImageConversionFlag] = Qt.AutoColor): argument 1 has unexpected type 'QRectF'
  drawImage(self, QPoint, QImage, QRect, flags: Union[Qt.ImageConversionFlags, Qt.ImageConversionFlag] = Qt.AutoColor): argument 1 has unexpected type 'QRectF'
  drawImage(self, QRectF, QImage): argument 2 has unexpected type 'NoneType'
  drawImage(self, QRect, QImage): argument 1 has unexpected type 'QRectF'
  drawImage(self, Union[QPointF, QPoint], QImage): argument 1 has unexpected type 'QRectF'
  drawImage(self, QPoint, QImage): argument 1 has unexpected type 'QRectF'
  drawImage(self, int, int, QImage, sx: int = 0, sy: int = 0, sw: int = -1, sh: int = -1, flags: Union[Qt.ImageConversionFlags, Qt.ImageConversionFlag] = Qt.AutoColor): argument 1 has unexpected type 'QRectF'
ERROR:root:Traceback (most recent call last):
  File "make_binary.py", line 30, in <module>
    sys.exit(app.exec_())
SystemExit: 0

**Comment by Jhsmit** [comment]
See also: https://groups.google.com/forum/#!topic/pyqtgraph/ajykxBvysEc

**Comment by Jhsmit** [comment]
In general: dont update the GUI from anything but the main thread
